build_from:
  amd64: registry.cn-hangzhou.aliyuncs.com/skyview/skyview-cpu:0.7.3
labels:
  org.opencontainers.image.title: 云瞰 SkyView Home Assistant Add-on
  org.opencontainers.image.source: https://yun-kan.com
  org.opencontainers.image.licenses: Proprietary
args: {}
