build_from:
  amd64: registry.cn-hangzhou.aliyuncs.com/skyview/skyview-openvino:0.7.8
labels:
  org.opencontainers.image.title: 云瞰 VMS Home Assistant Add-on (OpenVINO)
  org.opencontainers.image.source: https://yun-kan.com
  org.opencontainers.image.licenses: Proprietary
args: {}
